name: Databricks Bundle CI/CD

on:
  push:
    branches:
      - dev

  release:
    types: [published]

jobs:

  deploy-dev:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare wheel (if exists)
        run: |
          if [ -f dist/mypkg.whl ]; then
            SHA=${GITHUB_SHA::7}
            mv dist/mypkg.whl dist/mypkg-${SHA}.whl
            echo "WHEEL_FILE=mypkg-${SHA}.whl" >> $GITHUB_ENV
          else
            echo "WHEEL_FILE=" >> $GITHUB_ENV
          fi

      - name: Run tests
        run: pytest tests/

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Verify Databricks CLI
        run: |
          databricks version
          databricks bundle --help

      - name: Deploy bundle to DEV
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_DEV_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_DEV_TOKEN }}
        run: |
          databricks bundle deploy -t dev \
            -v wheel_file=${WHEEL_FILE} \
            -v release_version=${GITHUB_SHA::7}

  
  deploy-release:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        env: [qa, prod]

    steps:
      - name: Checkout release tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Prepare wheel (if exists)
        run: |
          if [ -f dist/mypkg.whl ]; then
            SHA=${GITHUB_SHA::7}
            mv dist/mypkg.whl dist/mypkg-${SHA}.whl
            echo "WHEEL_FILE=mypkg-${SHA}.whl" >> $GITHUB_ENV
          else
            echo "WHEEL_FILE=" >> $GITHUB_ENV
          fi

      - name: Run tests
        run: pytest tests/

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Verify Databricks CLI
        run: |
          databricks version
          databricks bundle --help

      - name: Deploy bundle to ${{ matrix.env }}
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_DEV_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_DEV_TOKEN }}
        run: |
          databricks bundle deploy -t ${{ matrix.env }} \
            -v wheel_file=${WHEEL_FILE} \
            -v release_version=${GITHUB_REF_NAME}
