# name: Build & Deploy Databricks Job

# on:
#   push:
#     branches: [dev]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4

#       - name: Install Python tooling
#         run: |
#           pip install pytest build

#       - name: Run tests
#         run: pytest tests/

#       - name: Install Databricks CLI
#         run: |
#           curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh


#       # - name: Build wheel
#       #   run: python -m build

#       # - name: Configure Databricks
#       #   run: |
#       #     databricks configure --token <<EOF
#       #     ${{ secrets.DATABRICKS_HOST }}
#       #     ${{ secrets.DATABRICKS_TOKEN }}
#       #     EOF

#       - name: Verify Databricks CLI
#         run: |
#           databricks version
#           databricks bundle --help

#       - name: Deploy Databricks bundle
#         env:
#           DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
#           DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

#         run: |
#           if [[ "${GITHUB_REF_NAME}" == "dev" ]]; then
#             echo "Deploying to DEV"
#             databricks bundle validate -t dev
#             databricks bundle deploy -t dev
#           else
#             echo "Deploying to PROD"
#             databricks bundle validate -t prod
#             databricks bundle deploy -t prod
#           fi
